### ISSUE TITLE
avoid multiple random generator in xperandom.py

### ISSUE THREAD

**Issue by csgro** [lucabaldini/pyxpe#12]
Current default engine is native python "random" module, but theta and phi uses numpy "random" module.
This is bad for seeding and consistency, we should stick to one default generator.

**Comment by csgro** [comment]
As temporary fix for seeding we can seed both in set_seed:

def set_seed(self, seed=None):
        self.engine.seed(seed)
        np.random.seed(seed)

**Comment by lucabaldini** [comment]
The Python native generator is notoriously small and does not allow vectorization---I'd go with numpy without any hesitation.

My 2 cents,
Luca

**Comment by csgro** [comment]
Now using numpy random, after commit 2331b5c 
Closing this issue.
