### ISSUE TITLE
'file' does not exist in python 3.5 and binio does not work

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/pyxpe#17]
E:\xpe\xpedaq>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyxpe.recon.binio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\xpe\pyxpe\pyxpe\recon\binio.py", line 33, in <module>
    class xpeBinaryFileBase(file):
NameError: name 'file' is not defined

**Comment by csgro** [comment]
The easiest way to fix this is avoid file inheritance and re-implement relevant methods.
See commit a560812.
tested on linux with python2.7 and win with python3.5 using xpedisplay

**Comment by lucabaldini** [comment]
Ok, with this fix, the xpeBinaryFileBase class is not an iterator and the next() method must be called explicitely in event loop.

**Comment by lucabaldini** [comment]
ok, that's was just a wrong return in __next__ 
closing again
